-- заполняем таблицу MPA
INSERT INTO MPA SET MPA_ID = 1, FILM_RATING = 'G';
INSERT INTO MPA SET MPA_ID = 2, FILM_RATING = 'PG';
INSERT INTO MPA SET MPA_ID = 3, FILM_RATING = 'PG-13';
INSERT INTO MPA SET MPA_ID = 4, FILM_RATING = 'R';
INSERT INTO MPA SET MPA_ID = 5, FILM_RATING = 'NC-17';

-- заполняем таблицу GENRE
INSERT INTO GENRE SET GENRE_ID = 1, GENRE_TITLE = 'Комедия';
INSERT INTO GENRE SET GENRE_ID = 2, GENRE_TITLE = 'Драма';
INSERT INTO GENRE SET GENRE_ID = 3, GENRE_TITLE = 'Мультфильм';
INSERT INTO GENRE SET GENRE_ID = 4, GENRE_TITLE = 'Триллер';
INSERT INTO GENRE SET GENRE_ID = 5, GENRE_TITLE = 'Документальный';
INSERT INTO GENRE SET GENRE_ID = 6, GENRE_TITLE = 'Боевик';